INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('aplicador', '1', 'APLICADOR');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('gestor', '1', 'APLICADOR');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('kaua', '1', 'GESTOR');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('admin', '1', 'ADMIN');

INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (1, 1, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (2, 2, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (1, 2, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (3, 2, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (1, 3, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (4, 1, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (4, 1, CURRENT_TIMESTAMP);
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO) VALUES (5, 1, CURRENT_TIMESTAMP);