INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('aplicador', 'aplicador', 'Aplicador');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('aplicador1', 'aplicador1', 'Aplicador');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('aplicador2', 'aplicador2', 'Aplicador');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('gestor', 'gestor', 'Gestor');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('gestor1', 'gestor1', 'Gestor');
INSERT INTO USUARIO (LOGIN, SENHA, CARGO) VALUES ('senac', 'alunossenac', 'Admin');

INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (1, 1, CURRENT_TIMESTAMP, '1', 'Admin');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (2, 2, CURRENT_TIMESTAMP, '2', 'Aplicador');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (1, 2, CURRENT_TIMESTAMP, '3', 'Aplicador');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (3, 2, CURRENT_TIMESTAMP, '4', 'Aplicador');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (1, 3, CURRENT_TIMESTAMP, '5', 'Admin');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (4, 1, CURRENT_TIMESTAMP, '1', 'Aplicador');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (4, 1, CURRENT_TIMESTAMP, '2', 'Aplicador');
INSERT INTO VACINA_BAIRRO (BAIRRO_ID, VACINA_ID, DATA_APLICACAO, DOSE, APLICADOR) VALUES (5, 1, CURRENT_TIMESTAMP, '3', 'Aplicador');