INSERT INTO BAIRRO (nome) VALUES ('Bom Pastor');
INSERT INTO BAIRRO (nome) VALUES ('Humaitá de Cima');
INSERT INTO BAIRRO (nome) VALUES ('Humaitá');
INSERT INTO BAIRRO (nome) VALUES ('Campestre');
INSERT INTO BAIRRO (nome) VALUES ('Congonhas');
INSERT INTO BAIRRO (nome) VALUES ('Fábio Silva');
INSERT INTO BAIRRO (nome) VALUES ('Guarda Margem Esquerda');
INSERT INTO BAIRRO (nome) VALUES ('KM 60');
INSERT INTO BAIRRO (nome) VALUES ('KM 63');
INSERT INTO BAIRRO (nome) VALUES ('Madre');
INSERT INTO BAIRRO (nome) VALUES ('São Bernardo');
INSERT INTO BAIRRO (nome) VALUES ('São João');
INSERT INTO BAIRRO (nome) VALUES ('Vila Esperança');
INSERT INTO BAIRRO (nome) VALUES ('Morrotes');
INSERT INTO BAIRRO (nome) VALUES ('Dehon');
INSERT INTO BAIRRO (nome) VALUES ('Revoredo');
INSERT INTO BAIRRO (nome) VALUES ('Caruru');
INSERT INTO BAIRRO (nome) VALUES ('São Martinho');
INSERT INTO BAIRRO (nome) VALUES ('Cruzeiro');
INSERT INTO BAIRRO (nome) VALUES ('Fábio Silva');
INSERT INTO BAIRRO (nome) VALUES ('Monte Castelo');
INSERT INTO BAIRRO (nome) VALUES ('Oficinas');
INSERT INTO BAIRRO (nome) VALUES ('Centro');
INSERT INTO BAIRRO (nome) VALUES ('Santo Antônio de Pádua');
INSERT INTO BAIRRO (nome) VALUES ('Vila Moema');
INSERT INTO BAIRRO (nome) VALUES ('Recife');
INSERT INTO BAIRRO (nome) VALUES ('Passagem');
INSERT INTO BAIRRO (nome) VALUES ('Passo do gado');
INSERT INTO BAIRRO (nome) VALUES ('Praia Redonda');
INSERT INTO BAIRRO (nome) VALUES ('São Clemente');
INSERT INTO BAIRRO (nome) VALUES ('São Cristóvão');
INSERT INTO BAIRRO (nome) VALUES ('Congonhas');
INSERT INTO BAIRRO (nome) VALUES ('São Martinho');

INSERT INTO VACINA (NOME) VALUES ('BCG');
INSERT INTO VACINA (NOME) VALUES ('Hepatite B');
INSERT INTO VACINA (NOME) VALUES ('Penta (DTP/Hib/Hep B)');
INSERT INTO VACINA (NOME) VALUES ('Vacina Pneumocócica 10 valente');
INSERT INTO VACINA (NOME) VALUES ('VIP (Vacina Inativada Poliomielite)');
INSERT INTO VACINA (NOME) VALUES ('VRH (Vacina Rotavírus Humano)');
INSERT INTO VACINA (NOME) VALUES ('Meningocócica C (conjugada)');
INSERT INTO VACINA (NOME) VALUES ('VOP (Vacina Oral Poliomielite)');
INSERT INTO VACINA (NOME) VALUES ('Febre amarela');
INSERT INTO VACINA (NOME) VALUES ('Tríplice viral (Sarampo, rubéola, caxumba)');
INSERT INTO VACINA (NOME) VALUES ('Tetraviral (Sarampo, rubéola, caxumba, varicela)');
INSERT INTO VACINA (NOME) VALUES ('Hepatite A');
INSERT INTO VACINA (NOME) VALUES ('DTP (tríplice bacteriana)');
INSERT INTO VACINA (NOME) VALUES ('Varicela');
INSERT INTO VACINA (NOME) VALUES ('HPV quadrivalente (Papilomavírus Humano)');
